/**:
  ros__parameters:
    output_color_topic: /sensors/camera/color/image
    output_depth_topic: /sensors/camera/depth/image
    output_camera_info_topic: /sensors/camera/depth/camera_info
    output_points_topic: /sensors/camera/points
    status_topic: /sensors/camera/status
    freshness_timeout_sec: 1.0
    drop_invalid_messages: true
